-- ==========================================================
-- HAWASSA UNIFIED CAMPUS EVENT MANAGEMENT SYSTEM (HUCEMS)
-- DATABASE SNAPSHOT ARCHIVE
-- Generated at  : 2026-08-22 20:14:39 UTC
-- Generated by  : Master SuperAdmin (SuperAdmin)
-- Database      : university_event_management
-- Engine        : MySQL 8.0 / MySql.EntityFrameworkCore 10.0.9
-- Operator Notes: Pre-verification live snapshot
-- ==========================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- [TABLE: users] Verified Records: 40
-- [TABLE: events] Verified Records: 11
-- [TABLE: departments] Verified Records: 5
-- [TABLE: venues] Verified Records: 5

SET FOREIGN_KEY_CHECKS = 1;
-- [END OF BACKUP SNAPSHOT]
